# Generated by Django 3.1.4 on 2021-01-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(help_text='First name of the user', max_length=20)),
                ('last_name', models.CharField(help_text='Last name of the user', max_length=20)),
            ],
        ),
    ]
