# Generated by Django 3.1.4 on 2021-01-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formInterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Confirm_Password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Email_Id',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude of Current Location'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude of Current Location'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userdata',
            name='State',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Terms_and_Conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='First_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
