# Generated by Django 3.1.4 on 2021-01-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formInterface', '0002_auto_20210103_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
